# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aiops.v1 import aiops_core_pb2 as aiops_dot_v1_dot_aiops__core__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in aiops/v1/aiops_core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIOpsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/aiops.v1.AIOpsService/HealthCheck',
                request_serializer=aiops_dot_v1_dot_aiops__core__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=aiops_dot_v1_dot_aiops__core__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_stream(
                '/aiops.v1.AIOpsService/Chat',
                request_serializer=aiops_dot_v1_dot_aiops__core__pb2.ChatRequest.SerializeToString,
                response_deserializer=aiops_dot_v1_dot_aiops__core__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.PredictLoad = channel.unary_unary(
                '/aiops.v1.AIOpsService/PredictLoad',
                request_serializer=aiops_dot_v1_dot_aiops__core__pb2.LoadPredictionRequest.SerializeToString,
                response_deserializer=aiops_dot_v1_dot_aiops__core__pb2.LoadPredictionResponse.FromString,
                _registered_method=True)


class AIOpsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictLoad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIOpsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=aiops_dot_v1_dot_aiops__core__pb2.HealthCheckRequest.FromString,
                    response_serializer=aiops_dot_v1_dot_aiops__core__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=aiops_dot_v1_dot_aiops__core__pb2.ChatRequest.FromString,
                    response_serializer=aiops_dot_v1_dot_aiops__core__pb2.ChatResponse.SerializeToString,
            ),
            'PredictLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictLoad,
                    request_deserializer=aiops_dot_v1_dot_aiops__core__pb2.LoadPredictionRequest.FromString,
                    response_serializer=aiops_dot_v1_dot_aiops__core__pb2.LoadPredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiops.v1.AIOpsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiops.v1.AIOpsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIOpsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiops.v1.AIOpsService/HealthCheck',
            aiops_dot_v1_dot_aiops__core__pb2.HealthCheckRequest.SerializeToString,
            aiops_dot_v1_dot_aiops__core__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aiops.v1.AIOpsService/Chat',
            aiops_dot_v1_dot_aiops__core__pb2.ChatRequest.SerializeToString,
            aiops_dot_v1_dot_aiops__core__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiops.v1.AIOpsService/PredictLoad',
            aiops_dot_v1_dot_aiops__core__pb2.LoadPredictionRequest.SerializeToString,
            aiops_dot_v1_dot_aiops__core__pb2.LoadPredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
