# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aiops/v1/aiops_core.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aiops/v1/aiops_core.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61iops/v1/aiops_core.proto\x12\x08\x61iops.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"e\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"R\n\x0b\x43hatRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\"r\n\x0c\x43hatResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x17\n\x0fprocessing_time\x18\x05 \x01(\x02\"R\n\x15LoadPredictionRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63urrent_load\x18\x02 \x01(\x02\x12\r\n\x05hours\x18\x03 \x01(\x05\"_\n\x16LoadPredictionResponse\x12-\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x18.aiops.v1.LoadPrediction\x12\x16\n\x0erecommendation\x18\x02 \x01(\t\"J\n\x0eLoadPrediction\x12\x0c\n\x04hour\x18\x01 \x01(\x05\x12\x16\n\x0epredicted_load\x18\x02 \x01(\x02\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x32\xe5\x01\n\x0c\x41IOpsService\x12J\n\x0bHealthCheck\x12\x1c.aiops.v1.HealthCheckRequest\x1a\x1d.aiops.v1.HealthCheckResponse\x12\x37\n\x04\x43hat\x12\x15.aiops.v1.ChatRequest\x1a\x16.aiops.v1.ChatResponse0\x01\x12P\n\x0bPredictLoad\x12\x1f.aiops.v1.LoadPredictionRequest\x1a .aiops.v1.LoadPredictionResponseB<Z:github.com/GoSimplicity/AI-CloudOps/proto/aiops/v1;aiopsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aiops.v1.aiops_core_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/GoSimplicity/AI-CloudOps/proto/aiops/v1;aiopsv1'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=72
  _globals['_HEALTHCHECKREQUEST']._serialized_end=109
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=111
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=212
  _globals['_CHATREQUEST']._serialized_start=214
  _globals['_CHATREQUEST']._serialized_end=296
  _globals['_CHATRESPONSE']._serialized_start=298
  _globals['_CHATRESPONSE']._serialized_end=412
  _globals['_LOADPREDICTIONREQUEST']._serialized_start=414
  _globals['_LOADPREDICTIONREQUEST']._serialized_end=496
  _globals['_LOADPREDICTIONRESPONSE']._serialized_start=498
  _globals['_LOADPREDICTIONRESPONSE']._serialized_end=593
  _globals['_LOADPREDICTION']._serialized_start=595
  _globals['_LOADPREDICTION']._serialized_end=669
  _globals['_AIOPSSERVICE']._serialized_start=672
  _globals['_AIOPSSERVICE']._serialized_end=901
# @@protoc_insertion_point(module_scope)
